# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "platform-stdweb"
version         = "0.0.0"
publish         = false
edition         = "2018"

[dependencies]
platform-common = { path = "../common" }

[[bin]]
name            = "platform-stdweb"
path            = "stdweb.rs"
