image:
  - Visual Studio 2019

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set RUST_BACKTRACE=1
  - wsl --list || ver >NUL 2>NUL
  - wslconfig /list || ver >NUL 2>NUL
  - reg query HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss /s
  - powershell Get-AppxPackage -Name *Ubuntu*
  - rustc -V
  - cargo -V
  - ver

build_script:
  - cargo build --release

test_script:
  - cargo test
  - cd example/multiplatform
  - cargo container setup
  - cargo container build --config debug --config release --skip-install
  - cargo container test  --config debug --config release --skip-install
