language: rust
rust:
  - 1.47.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: 1.47.0
    - rust: beta
    - rust: nightly
before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-mingw-w64-x86-64 libssl-dev
  - rustup target add x86_64-pc-windows-gnu
  - rustup target add wasm32-unknown-unknown
script:
  - cargo build --release
  - |
    export PATH=$(pwd)/target/release:$PATH
    cd example/multiplatform
    cargo container build
    cargo container test
