language: rust
rust:
  - 1.47.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: 1.47.0
    - rust: beta
    - rust: nightly
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libssl-dev
script:
  - cargo build --release
  - export PATH=$(pwd)/target/release:$PATH
  - cd example/multiplatform
  - cargo container setup
  - cargo container build --config debug --config release
  - cargo container test  --config debug --config release
