language: rust
rust:
  - stable
script:
  - cargo build --release
  - export PATH=$(pwd)/target/release:$PATH
  - cd example/multiplatform
  - cargo container setup
  - cargo container build --config debug --config release
  - cargo container test  --config debug --config release
