# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "alpha"
version         = "0.0.0"
publish         = false
edition         = "2018"

[dependencies]
app-common      = { path = "../../app-common" }

[lib]
path            = "alpha.rs"
