[local-install]
platform-console    = { path = "platforms/console" }
platform-opendingux = { path = "platforms/opendingux" }
platform-stdweb     = { path = "platforms/stdweb"  }
platform-web-sys    = { path = "platforms/web-sys" }
platform-windows    = { path = "platforms/windows" }

[workspace]
members = [
    "app-common",
    "apps/*",
]

[[build]]
crates  = ["alpha", "beta", "delta"]
tools   = ["platform-console", "platform-opendingux", "platform-stdweb", "platform-web-sys", "platform-windows"]

[profile]
dev     .panic = "abort"
release .panic = "abort"
test    .panic = "abort"
bench   .panic = "abort"
