# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "platform-opendingux"
version         = "0.0.0"
publish         = false
edition         = "2018"

[dependencies]
platform-common = { path = "../common" }

[target.'cfg(windows)'.dependencies]
wio             = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version         = "0.3.9"
features = [
    "impl-default",                                                         # impl-*
    "rpcdce", "winerror", "wtypesbase",                                     # winapi::shared
    "combaseapi", "oaidl", "objbase", "objidlbase", "oleauto", "wbemcli",   # winapi::um
]

[[bin]]
name            = "platform-opendingux"
path            = "opendingux.rs"
