# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "platform-opendingux"
version         = "0.0.0"
publish         = false
edition         = "2018"

[dependencies]
platform-common = { path = "../common" }

[target.'cfg(windows)'.dependencies]
appx            = "0.1"
wio             = "0.2"
wslapi          = "0.1.2"
wchar           = "0.6"

[target.'cfg(windows)'.dependencies.winapi]
version         = "0.3.9"
features = [
    # impl-*
    "impl-default",

    # shared
    "rpcdce",
    "winerror",
    "wtypesbase",

    # um
    "combaseapi",
    "oaidl",
    "objbase",
    "objidlbase",
    "oleauto",
    "shellapi",
    "wbemcli",
    "winuser",

    # winrt
    "roapi",
]

[[bin]]
name            = "platform-opendingux"
path            = "opendingux.rs"
