# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "platform-common"
version         = "0.0.0"
publish         = false
edition         = "2018"

[lib]
path            = "common.rs"

[dependencies]
mmrbi           = { git = "https://github.com/MaulingMonkey/mmrbi", rev = "fc83ac2937a6919aa7a5f2425311877f32c93cff" }
#mmrbi           = "0.0.8"
#mmrbi           = { path = "../../../../../mmrbi" }
