# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "platform-common"
version         = "0.0.0"
publish         = false
edition         = "2018"

[lib]
path            = "common.rs"

[dependencies]
cargo-local-install = "0.1.9"
libflate        = "1.0.3"
mmrbi           = "0.0.9"
reqwest         = { version = "0.10", features = ["blocking"] }
sha2            = "0.9.1"
tar             = "0.4.30"
