name: rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test CLI
      run: cargo test
    - name: Build CLI
      run: cargo build --release
    - name: Example Multiplatform Setup
      run: |
        PATH=$(pwd)/target/release:$PATH
        cd example/multiplatform
        cargo container setup
    - name: Example Multiplatform Build
      run: |
        PATH=$(pwd)/target/release:$PATH
        cd example/multiplatform
        cargo container build --config debug --config release
    - name: Example Multiplatform Test
      run: |
        PATH=$(pwd)/target/release:$PATH
        cd example/multiplatform
        cargo container test  --config debug --config release
