name: rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test CLI
      run: cargo test --verbose
    - name: Build/Setup CLI
      run: |
        cargo build --release --verbose
        export PATH=$(pwd)/target/release:$PATH
        cd example/multiplatform
    - name: Example Multiplatform Setup
      run: cargo container setup
    - name: Example Multiplatform Build
      run: cargo container build --config debug --config release
    - name: Example Multiplatform Test
      run: cargo container test  --config debug --config release
